import type { Brand } from "./types";

export const shopIntro = {
  title: "IZZA",
  tagline: "A curated boutique at IZZA Hotel, Marrakech",
  description:
    "IZZA Boutique is a curated destination for those seeking authentic, artisanal, and thoughtfully designed objects. A celebration of Moroccan craftsmanship, heritage, and innovation, where traditional know-how meets contemporary design. From textiles and decorative pieces to bespoke accessories, each item reflects the fusion of skill, creativity, and contemporary aesthetics.",
};

export const siteImages = {
  hero: "izza-shop-full-selection-27",
  boutique: [
    "izza-shop-full-selection-51",
    "izza-shop-full-selection-28",
    "izza-shop-full-selection-29",
  ],
  botanical: "izza-shop-full-selection-16",
};

export const brands: Brand[] = [
  {
    slug: "develasco",
    name: "Develasco",
    tagline: "Contemporary caftans rooted in Moroccan craft",
    categoryLabel: "Clothing & Accessories",
    material: "Fabric & Timmitry",
    founder: "Sanaa & Wafaa Redouani",
    instagram: "https://www.instagram.com/develasco.ma/",
    story: "Develasco is a Moroccan fashion brand blending contemporary style with refined craftsmanship. Based in Marrakech and Tangier, the brand creates ready-to-wear pieces that combine elegance, simplicity, and modern silhouettes. Its approach highlights quality materials and timeless design suited to an effortless lifestyle. Through its collections, Develasco reflects a modern vision of Moroccan fashion rooted in authenticity and sophistication.",
    images: [
      { src: "izza-shop-full-selection-37", alt: "Draped copper caftan with blue beaded necklace", role: "hero", aspect: "portrait" },
      { src: "izza-shop-full-selection-40", alt: "Caftan neckline detail with geometric earring and beaded necklace", role: "detail", aspect: "portrait", sharedWith: ["yoomi", "n9cra"] },
      { src: "izza-shop-full-selection-41", alt: "Full-length draped copper caftan with dramatic pleating", role: "detail", aspect: "portrait" },
    ],
    isHouseBrand: false,
  },
  {
    slug: "kasbah-chic",
    name: "Kasbah Chic",
    tagline: "Handwoven accessories from the heart of Marrakech",
    categoryLabel: "Accessories",
    material: "Woven Synthetic Leather & Fiber",
    founder: "Patrizia Bell-Banner",
    instagram: "https://www.instagram.com/kasbah_chic/",
    story: "Kasbah Chic celebrates the skill and creativity of Moroccan artisans at the heart of Marrakech. For decades, these artisans have perfected leatherwork, weaving, and other traditional crafts, transforming noble materials into unique, handcrafted objects. Each piece reflects a careful blend of ancestral techniques and contemporary design, ensuring individuality and authenticity. More than accessories, Kasbah Chic\u2019s creations honor Moroccan craftsmanship and the dedication, passion, and artistry of the artisans themselves.",
    images: [
      { src: "izza-shop-full-selection-01", alt: "Boutique wardrobe displaying curated clothing and woven accessories", role: "hero", aspect: "portrait" },
      { src: "izza-shop-full-selection-49", alt: "Full wardrobe display with handwoven bags and accessories", role: "atmosphere", aspect: "portrait" },
      { src: "izzashop-day1-25", alt: "Teal woven clutch bag with silver jewelry on sunlit stone", role: "styled", aspect: "portrait", sharedWith: ["she"] },
    ],
    isHouseBrand: false,
  },
  {
    slug: "she",
    name: "SHE",
    tagline: "Sculptural silver jewelry inspired by architecture",
    categoryLabel: "Jewelry",
    material: "Silver",
    founder: "Cherise Dobbins",
    instagram: "https://www.instagram.com/she_archives/",
    website: "https://www.she-archives.com/",
    story: "SHE is a contemporary jewelry brand founded in Marrakech, creating bold sculptural pieces inspired by architectural forms. Drawing on North African and Mediterranean geometry, the brand designs structured statement jewelry that blends artistic expression with everyday wear. Each piece is conceived as a personal talisman, guided by balance, proportion, and form rather than excessive ornamentation. Produced in limited editions, SHE\u2019s creations are designed to feel enduring, substantial, and timeless.",
    images: [
      { src: "izzashop-day1-25", alt: "Silver necklace and teal earrings on natural stone", role: "hero", aspect: "portrait", sharedWith: ["kasbah-chic"] },
      { src: "izza-shop-full-selection-48", alt: "Jewelry display table with necklaces and glass cases", role: "styled", aspect: "portrait" },
      { src: "izza-shop-full-selection-23", alt: "Curated shelf display with jewelry, ceramics, and artisan objects", role: "atmosphere", aspect: "portrait", sharedWith: ["izza-ceramic", "izza-perfume"] },
    ],
    isHouseBrand: false,
  },
  {
    slug: "travel",
    name: "Travel",
    tagline: "Essentials for the modern nomad",
    categoryLabel: "Clothing",
    material: "Fabric & Timmitry",
    founder: "Patrice Kouadio",
    instagram: "https://www.instagram.com/shop__travel/",
    story: "Travel Brand is a lifestyle label born from a passion for exploration, freedom, and contemporary aesthetics. Rooted in the spirit of wanderlust, the brand offers thoughtfully curated travel essentials designed for today\u2019s modern nomad. With clean lines, quality materials, and versatile silhouettes, each piece blends function with effortless style. Travel Brand invites you to carry intentional design with you \u2014 wherever the journey leads.",
    images: [
      { src: "izza-shop-full-selection-42", alt: "Clothing rack with curated shirts and ceramic pitcher above", role: "hero", aspect: "portrait", sharedWith: ["fanny-lopez-studio"] },
      { src: "izza-shop-full-selection-29", alt: "Boutique interior with shelves of curated products and art", role: "atmosphere", aspect: "portrait" },
    ],
    isHouseBrand: false,
  },
  {
    slug: "lalla",
    name: "Lalla",
    tagline: "Playful handmade bags from Marrakech",
    categoryLabel: "Accessories",
    material: "Towel & Textile",
    founder: "Laetitia Trouillet",
    instagram: "https://www.instagram.com/lallamarrakech/",
    website: "https://shoplalla.com/",
    story: "LALLA is a lifestyle accessories brand founded by Laetitia Trouillet, inspired by her love of travel, culture, and Moroccan craftsmanship. Based in Marrakech since 2005, the brand creates chic and effortless bags and accessories handmade by local artisans. Its colorful and playful designs combine practicality with a relaxed, global aesthetic. Signature collections such as EPONGE and CARPET have become iconic pieces, now carried in stylish boutiques around the world.",
    images: [
      { src: "izza-shop-full-selection-28", alt: "Handmade bag on display stand in boutique with Moorish archway", role: "hero", aspect: "landscape" },
      { src: "izzashop-day1-21", alt: "Boutique interior with shelving and artisan products", role: "atmosphere", aspect: "landscape" },
    ],
    isHouseBrand: false,
  },
  {
    slug: "matala",
    name: "Matala",
    tagline: "Where Marrakech tradition meets modern living",
    categoryLabel: "Clothing",
    material: "Textile & Brodery",
    instagram: "https://www.instagram.com/matala.official/",
    website: "https://matalamarrakech.com/",
    story: "Matala Marrakech is a contemporary lifestyle brand inspired by the vibrant spirit, colors, and craftsmanship of Marrakech. Rooted in Moroccan culture, the brand reinterprets traditional aesthetics through modern design, creating objects that blend heritage with contemporary living. Its collections celebrate artisanal techniques and carefully crafted materials, reflecting the city\u2019s rich creative energy. Through its pieces, Matala captures the essence of Marrakech \u2014 where tradition, craftsmanship, and modern lifestyle meet.",
    images: [
      { src: "izza-shop-full-selection-50", alt: "Boutique wardrobe with colorful garments and a browsing visitor", role: "hero", aspect: "portrait" },
      { src: "izza-shop-full-selection-01", alt: "Wardrobe detail with hanging clothing and shelved accessories", role: "atmosphere", aspect: "portrait" },
    ],
    isHouseBrand: false,
  },
  {
    slug: "res-ipsa",
    name: "Res Ipsa",
    tagline: "Story-rich pieces from a globally inspired atelier",
    categoryLabel: "Clothing & Accessories",
    material: "Fabric",
    instagram: "https://www.instagram.com/explore/locations/134680709719862/res-ipsa/",
    website: "https://www.resipsausa.com/",
    story: "Res Ipsa is a globally inspired lifestyle brand born from a passion for travel, craftsmanship, and mindful design. Founded in 2013 by two former lawyers who sought to create distinctive, story-rich products, the brand blends heritage techniques with sustainably sourced and repurposed materials. Known for handmade shoes, bags, accessories, and home goods, each piece reflects a quiet luxury rooted in the spirit of discovery and self-expression. With ateliers and retail spaces across the world \u2014 including Marrakech \u2014 Res Ipsa invites you to carry intentional design wherever you go.",
    images: [
      { src: "izza-shop-full-selection-49", alt: "Full boutique wardrobe with curated clothing, bags, and accessories", role: "hero", aspect: "portrait" },
      { src: "izza-shop-full-selection-29", alt: "Wide boutique interior with art prints and product shelving", role: "atmosphere", aspect: "portrait" },
    ],
    isHouseBrand: false,
  },
  {
    slug: "n9cra",
    name: "N9CRA",
    tagline: "Bold jewelry exploring identity and symbolism",
    categoryLabel: "Jewelry",
    material: "Silver",
    founder: "Camelia Zaireg",
    instagram: "https://www.instagram.com/n9cra/",
    website: "https://n9cra.com/",
    story: "N9CRA is a contemporary jewelry brand that explores identity, symbolism, and personal expression through bold design. Rooted in a creative and independent spirit, the brand creates distinctive pieces that function as both adornment and statement. Each collection reflects a dialogue between modern aesthetics and cultural narratives. Through its objects, N9CRA invites wearers to express individuality and carry a piece of artistic identity.",
    images: [
      { src: "izza-shop-full-selection-06", alt: "Gold architectural earrings displayed on dark ceramic shell dishes", role: "hero", aspect: "portrait" },
      { src: "izza-shop-full-selection-02", alt: "Geometric gold earrings on dark green marble surface", role: "detail", aspect: "portrait" },
      { src: "izza-shop-full-selection-04", alt: "Brass geometric pendant held in open palm", role: "detail", aspect: "portrait" },
    ],
    isHouseBrand: false,
  },
  {
    slug: "fanny-lopez-studio",
    name: "Fanny Lopez Studio",
    tagline: "Sculptural ceramics bridging art and architecture",
    categoryLabel: "Home & Deco Objects",
    material: "Ceramic",
    founder: "Fanny Lopez",
    instagram: "https://www.instagram.com/fanny.lopez/",
    story: "Fanny Lopez is a French-Moroccan designer whose practice bridges art direction, textile art, and design. After leading the visual identity of the Montresso Art Foundation in Marrakech, she founded F\u2013L Studio, dedicated to art editions and visual identity. Based in Marrakech, her atelier showcases collaborations with Moroccan artisans, celebrating traditional craftsmanship and raw materials. Inspired by architecture, her work transforms everyday forms such as sieves, doors, and arches into unique embroidered and sculptural pieces.",
    images: [
      { src: "izza-shop-full-selection-36", alt: "Minimalist ceramic dinner set with cups, plates, and bowls in neutral tones", role: "hero", aspect: "portrait" },
      { src: "izza-shop-full-selection-43", alt: "Sculptural ceramic pitcher with wavy handle by a sunlit window", role: "detail", aspect: "portrait" },
      { src: "izza-shop-full-selection-44", alt: "Ceramic pitcher with artisan tag on tiled shelf", role: "detail", aspect: "portrait" },
    ],
    isHouseBrand: false,
  },
  {
    slug: "yoomi",
    name: "Yoomi",
    tagline: "Ethical accessories crafted with community spirit",
    categoryLabel: "Accessories",
    material: "Multi-Material",
    founder: "Florence Morgenstern",
    instagram: "https://www.instagram.com/yoomee.ch/",
    website: "https://yoomee.ch",
    story: "Yoomee is a lifestyle accessories brand founded by Florence Morgenstern and inspired by the beauty, people, and craftsmanship of Marrakech and Zurich. The brand works directly with local artisans, street artists, small workshops, and women\u2019s associations to create ethically produced, handcrafted objects. Its collections range from jewelry and keychains to bags and everyday accessories, blending contemporary design with traditional techniques. Through these collaborations, Yoomee celebrates craftsmanship while fostering meaningful, sustainable relationships with the communities behind each piece.",
    images: [
      { src: "izza-shop-full-selection-46", alt: "Colorful beaded necklaces in teal and yellow inside a glass display box", role: "hero", aspect: "portrait" },
      { src: "izza-shop-full-selection-45", alt: "Close-up of thread-wrapped beaded necklaces in glass case", role: "detail", aspect: "landscape" },
      { src: "izza-shop-full-selection-40", alt: "Copper caftan styled with blue and orange beaded necklace", role: "styled", aspect: "portrait", sharedWith: ["develasco"] },
    ],
    isHouseBrand: false,
  },
  {
    slug: "sania",
    name: "SANIA",
    tagline: "Ceramic art inspired by Moroccan and Spanish heritage",
    categoryLabel: "Deco Objects",
    material: "Ceramic",
    founder: "Rita Rivera & Amine Asselman",
    instagram: "https://www.instagram.com/saniaceramic/",
    website: "https://www.sania.ma/",
    story: "Sania creates exceptional decorative pieces, unique artworks, and commissioned design objects that blend art, design, and craft. Inspired by a shared heritage between Spain and Morocco, the brand draws on legends, mythology, and the magic of architectural and natural patrimony. Collaborating closely with local artisans, Sania revives ancestral production techniques, fostering a meaningful dialogue between tradition and contemporary creativity. Each piece embodies authenticity, quality, and beauty, achieved through a deliberate \u201Cslow work\u201D approach and meticulous craftsmanship.",
    images: [
      { src: "izza-shop-full-selection-55", alt: "Decorative ceramic cups and vase with bold arch patterns in terracotta and olive", role: "hero", aspect: "portrait" },
      { src: "izza-shop-full-selection-56", alt: "Three ceramic cups with arch motifs on marble pedestal in soft light", role: "detail", aspect: "portrait" },
    ],
    isHouseBrand: false,
  },
  {
    slug: "botanika",
    name: "Botanika",
    tagline: "Moroccan beauty rituals, naturally reimagined",
    categoryLabel: "Organic Beauty Care",
    instagram: "https://www.instagram.com/thebotanika/",
    story: "Inspired by ancestral Moroccan beauty rituals, The Botanika Marrakech creates innovative and effective skincare formulas using exclusively natural active ingredients. At the core of the brand is the synergy between argan leaf extract and argan oil, combining tradition with modern cosmetic expertise. IZZA\u2019s curated selection focuses on beauty and care products used within our spa and hammam rituals, enhanced by refined, organic-luxury packaging. Through thoughtful editorial content, the brand highlights the benefits and heritage of Moroccan wellness traditions, offering guests an authentic and sensorial spa experience.",
    images: [
      { src: "izza-shop-full-selection-30", alt: "Star-shaped amber soap bars in warm directional light", role: "hero", aspect: "portrait" },
      { src: "izza-shop-full-selection-32", alt: "Hand placing a star-shaped artisanal soap on a stack", role: "detail", aspect: "portrait" },
    ],
    isHouseBrand: false,
  },
  // --- IZZA House Brands ---
  {
    slug: "izza-ceramic",
    name: "Izza Ceramic",
    tagline: "Minimalist stoneware handcrafted in Marrakech",
    categoryLabel: "Homeware & Deco",
    material: "Stoneware Ceramic",
    founder: "IZZA Brand",
    story: "Introducing Izza\u2019s ceramic collection \u2014 a blend of minimalist design and artisanal craftsmanship. From dinner plates to espresso cups, each piece is meticulously handcrafted in Marrakech using stoneware ceramic, fired at high temperatures, and meeting European standards. With neutral colors and clean lines, every item embodies the essence of traditional Moroccan craftsmanship and seamlessly complements any modern living space.",
    images: [
      { src: "izza-shop-full-selection-36", alt: "Complete ceramic dinner set with cups, saucers, bowls, and plates", role: "hero", aspect: "portrait", sharedWith: ["fanny-lopez-studio"] },
      { src: "izza-shop-full-selection-23", alt: "Shelf display with ceramic pieces, perfume bottles, and woven accessories", role: "styled", aspect: "portrait", sharedWith: ["izza-perfume"] },
    ],
    isHouseBrand: true,
  },
  {
    slug: "izza-timmitry",
    name: "Izza Timmitry",
    tagline: "Ancestral Moroccan weaving made contemporary",
    categoryLabel: "Accessories",
    material: "Timmitry",
    founder: "IZZA Brand",
    story: "IZZA Timmitry Accessories offers a curated selection of artisanal accessories that blend Moroccan tradition with contemporary design. Each piece is handcrafted using Timmitry techniques, a Moroccan artisanal tradition that preserves centuries-old craftsmanship and local cultural heritage. Collaborating with skilled artisans, the brand transforms everyday objects into functional, elegant, and collectible accessories. Designed for both aesthetic appeal and practicality, IZZA Timmitry invites guests to carry a piece of Morocco\u2019s rich artisanal legacy wherever they go.",
    images: [
      { src: "izza-shop-full-selection-21", alt: "Colorful timmitry clutch bags with tassels alongside IZZA perfume bottles", role: "hero", aspect: "portrait", sharedWith: ["izza-perfume"] },
      { src: "izza-shop-full-selection-22", alt: "Timmitry clutch bags with crocheted slippers and perfume on display shelf", role: "detail", aspect: "portrait", sharedWith: ["izza-perfume", "yoomi"] },
      { src: "izza-shop-full-selection-14", alt: "Green tassel earrings and teal keychain on sunlit stone", role: "detail", aspect: "portrait" },
    ],
    isHouseBrand: true,
  },
  {
    slug: "izza-perfume",
    name: "Izza Perfume",
    tagline: "Invisible signatures of Marrakech",
    categoryLabel: "Interior Perfume",
    founder: "IZZA Brand",
    story: "At IZZA, fragrance is an invisible signature \u2014 a sensory memory of Marrakech. The Fig Tree was chosen as IZZA\u2019s emblematic scent for its mystical and grounding presence. Green, fruity and sun-warmed, it evokes shaded riads, ancient trees and the quiet strength of Mediterranean landscapes. Paired with it, Orange Blossom pays tribute to Marrakech\u2019s most iconic scent. Delicate, luminous and deeply evocative, it is a subtle nod to the city\u2019s olfactory heritage. Its soft floral notes capture the warmth, hospitality and elegance of Moroccan living.",
    images: [
      { src: "izza-shop-full-selection-26", alt: "IZZA perfume bottles on display shelf with slippers and brass pitcher", role: "hero", aspect: "portrait" },
      { src: "izza-shop-full-selection-24", alt: "Shelf arrangement with perfume bottles, necklace, and decorative objects", role: "detail", aspect: "landscape" },
    ],
    isHouseBrand: true,
  },
  {
    slug: "tamguerout",
    name: "Tamguerout Selection",
    tagline: "Ancient green pottery from the edge of the Sahara",
    categoryLabel: "Homeware & Deco",
    material: "Pottery",
    founder: "IZZA Brand",
    story: "Tamegroute is handmade pottery in a typical forest green color. Tamegroute originates from the village of the same name 16 km from Zagora, which is also the last place before the Sahara desert begins. Tamegroute pottery comes in all shapes and sizes: plates, bowls, candlesticks, vases, pots and beautiful abstract art objects. The technique hasn\u2019t changed and is passed on from one generation to the next, repeating the same gestures time after time.",
    images: [
      { src: "izza-shop-full-selection-09", alt: "Green Tamguerout vase on terracotta steps with tropical plants", role: "hero", aspect: "portrait" },
      { src: "izza-shop-full-selection-12", alt: "Green glazed Tamguerout vase on reflective surface with garden backdrop", role: "detail", aspect: "portrait" },
      { src: "izza-shop-full-selection-13", alt: "Two Tamguerout pottery vases in green and amber on dark surface", role: "detail", aspect: "portrait" },
    ],
    isHouseBrand: true,
  },
];
